name       : python-beautifulsoup4
version    : 4.8.1
release    : 10
source     :
    - https://files.pythonhosted.org/packages/86/cd/495c68f0536dcd25f016e006731ba7be72e072280305ec52590012c1e6f2/beautifulsoup4-4.8.1.tar.gz : 6135db2ba678168c07950f9a16c4031822c6f4aec75a65e0a97bc5ca09789931
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
builddeps  :
    - python-backports.functools_lru_cache
    - python-pytest
    - python-soupsieve
rundeps    :
    - python-soupsieve
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    pushd $PKG_BUILD_DIR/py3build
        2to3 -w bs4
        py.test3 -v
    popd
