name       : python-beautifulsoup4
version    : 4.9.3
release    : 13
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.9/beautifulsoup4-4.9.3.tar.gz : 84729e322ad1d5b4d25f805bfa05b902dd96450f43842c4e99067d5e1369eb25
homepage   : https://www.crummy.com/software/BeautifulSoup/
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4)
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
builddeps  :
    - python-backports.functools_lru_cache
    - python-pytest
    - python-soupsieve
rundeps    :
    - python-soupsieve
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    pushd $PKG_BUILD_DIR/py3build
        2to3 -w bs4
        py.test3 -v
    popd
