name       : python-beautifulsoup4
version    : 4.6.3
release    : 8
source     :
    - https://files.pythonhosted.org/packages/88/df/86bffad6309f74f3ff85ea69344a078fc30003270c8df6894fca7a3c72ff/beautifulsoup4-4.6.3.tar.gz : 90f8e61121d6ae58362ce3bed8cd997efb00c914eae0ff3d363c32f9a9822d10
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
builddeps  :
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    pushd $PKG_BUILD_DIR/py3build
        2to3 -w bs4
        py.test3 -v
    popd
