name        : python-beautifulsoup4
version     : 4.4.0
release     : 1
source     :
    - http://www.crummy.com/software/BeautifulSoup/bs4/download/4.4/beautifulsoup4-4.4.0.tar.gz : fad91da88f69438b9ba939ab1b2cabaa31b1d914f1cccb4bb157a993ed2917f6
license     : MIT
summary     : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
description : |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
builddeps  :
    - python-setuptools
    - python-chardet
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --optimize=1 --skip-build
