name       : python-beautifulsoup4
version    : 4.8.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/23/7b/37a477bc668068c23cb83e84191ee03709f1fa24d957b7d95083f10dda14/beautifulsoup4-4.8.0.tar.gz : 25288c9e176f354bf277c0a10aa96c782a6a18a17122dba2e8cec4a97e03343b
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
builddeps  :
    - python-backports.functools_lru_cache
    - python-pytest
    - python-soupsieve
rundeps    :
    - python-soupsieve
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    pushd $PKG_BUILD_DIR/py3build
        2to3 -w bs4
        py.test3 -v
    popd
