name       : python-beautifulsoup4
version    : 4.12.2
release    : 19
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.12/beautifulsoup4-4.12.2.tar.gz : 492bbc69dca35d12daac71c4db1bfff0c876c00ef4a2ffacce226d4638eb72da
homepage   : https://www.crummy.com/software/BeautifulSoup/
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4)
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-pytest
    - python-soupsieve
rundeps    :
    - python-soupsieve
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
