name       : python-beautifulsoup4
version    : 4.4.1
release    : 5
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.4/beautifulsoup4-4.4.1.tar.gz : 87d4013d0625d4789a4f56b8d79a04d5ce6db1152bb65f1d39744f7709a366b4
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects
    like screen-scraping
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
builddeps  :
    - python-setuptools
    - pkgconfig(python3)
    - pkgconfig(python-2.7)
    - python-chardet
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
