name       : python-beautifulsoup4
version    : 4.11.1
release    : 18
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.11/beautifulsoup4-4.11.1.tar.gz : ad9aa55b65ef2808eb405f46cf74df7fcb7044d5cbc26487f96eb2ef2e436693
homepage   : https://www.crummy.com/software/BeautifulSoup/
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4)
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
builddeps  :
    - python-pytest
    - python-soupsieve
rundeps    :
    - python-soupsieve
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
