name       : python-beautifulsoup4
version    : 4.6.0
release    : 6
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.6/beautifulsoup4-4.6.0.tar.gz : 808b6ac932dccb0a4126558f7dfdcf41710dd44a4ef497a0bb59a77f9f078e89
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
builddeps  :
    - python-setuptools
    - pkgconfig(python3)
    - pkgconfig(python-2.7)
    - python-chardet
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
