name       : python-beautifulsoup4
version    : 4.10.0
release    : 16
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.10/beautifulsoup4-4.10.0.tar.gz : fa73e5d0578d24eebee2b335a1677805b225e01654861ccf98e5be8ee1d3ceb7
homepage   : https://www.crummy.com/software/BeautifulSoup/
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4)
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
builddeps  :
    - python-pytest
    - python-soupsieve
rundeps    :
    - python-soupsieve
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    python3 -m unittest discover -s bs4
