name       : python-beautifulsoup4
version    : 4.4.1
release    : 4
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.4/beautifulsoup4-4.4.1.tar.gz : 87d4013d0625d4789a4f56b8d79a04d5ce6db1152bb65f1d39744f7709a366b4
license    : MIT
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping
builddeps  :
    - python-setuptools
    - pkgconfig(python-3.5)
    - pkgconfig(python-2.7)
    - python-chardet
setup      : |
    pushd ..
    cp -Rav beautifulsoup4-${version} py2
    cp -Rav beautifulsoup4-${version} py3
build      : |
    pushd ../py2
    %python_setup
    pushd ../py3
    %python3_setup
install    : |
    pushd ../py2
    %python_install
    pushd ../py3
    %python3_install
