name       : python-beautifulsoup4
version    : 4.9.1
release    : 12
source     :
    - https://www.crummy.com/software/BeautifulSoup/bs4/download/4.9/beautifulsoup4-4.9.1.tar.gz : 73cc4d115b96f79c7d77c1c7f7a0a8d4c57860d1041df407dd1aae7f07a77fd7
homepage   : https://www.crummy.com/software/BeautifulSoup/
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4)
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
builddeps  :
    - python-backports.functools_lru_cache
    - python-pytest
    - python-soupsieve
rundeps    :
    - python-soupsieve
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    pushd $PKG_BUILD_DIR/py3build
        2to3 -w bs4
        py.test3 -v
    popd
